export class matchplayerdetails
{
    playerId:number=0;
    name:string="";
    runs_score:number=0;
    balls_faced:number=0;
    fours:number=0;
    sixes:number=0;
    strike_rate:number=0;
    out:boolean=false
    overs_bowl:number=0;
    overs_bowl_display:string="0";
    runs_given:number=0;
    wickets_taken:number=0;
    maiden_over:number=0;
    economy:number=0;
    isBatted:boolean=false;
    isBowled:boolean=false;
    isStriker:boolean=false;
    isNonStriker:boolean=false;
    isCurrentBowler:boolean=false;
}